### ISSUE TITLE
Hi there team, issue trackers are so cool ! don't you think?

### ISSUE THREAD

**Issue by iamsortiz** [StaDatus/StaDatus-web#1]
# Tasks
- Create a github account
- Answer the question at title
  - with a comment on this issue
- Be nice
- Play it cool
- Hack the world

**Comment by iamsortiz** [comment]
@nathalievoeten take a look !

**Comment by iamsortiz** [comment]
@lvaquer ! stop slacking and answer !

**Comment by NathalieVoeten** [comment]
Yeah. It's like **awesome**

**Comment by lvaquer** [comment]
@iamsortiz we agree issue tracker is cool. But we have to start to define tasks for today ;)
Are you ready to start @NathalieVoeten ?
