### ISSUE TITLE
Review task state

### ISSUE THREAD

**Issue by lvaquer** [StaDatus/StaDatus-web#2]
What a is to review a task state:
- What we want to achieve with the task
- What we achieved
- Are we done with the task ? / Should we continue ?
- Should we create a next step in this direction ?
# Review tasks state of:
- [ ] [Google form](https://docs.google.com/forms/d/1Co8xxQvXZOTEOTCXARCot78GXf5Tm8YPj0XVJaxHfFA/edit#responses) #3 
- [ ] Mockups
- [ ] Questions for the viz's
# Backlog
- [ ] Decide project proposal

**Comment by iamsortiz** [comment]
Closed because the information is already reflected on the [project kanban](https://github.com/lvaquer/StaDatus/projects/1)
