### ISSUE TITLE
task - Google form

### ISSUE THREAD

**Issue by iamsortiz** [StaDatus/StaDatus-web#3]
- What we want to achieve with the task
- What we achieved
- Hare we done with the task ? / Should we continue ?
- Should we create a next step in this direction ?
  - [x] Analyze results from Google Form
  - [x] Extract conclusions from results

**Comment by NathalieVoeten** [comment]
**What do we want to achieve?**
- Get to know what people expect from our tool
- Get to know how much people already now about transparency

**Comment by NathalieVoeten** [comment]
**Analyzing results**

**Comment by NathalieVoeten** [comment]
**Conclusions**

**Comment by lvaquer** [comment]
**Analisis**
 [Google Form](https://docs.google.com/forms/d/1Co8xxQvXZOTEOTCXARCot78GXf5Tm8YPj0XVJaxHfFA/edit#responses)  el análisis es:
_Respecto a la Ley_
- La mayoría de los participantes no conocen la Ley de Transparencia 
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916459/c350563e-8594-11e6-9fee-b606edd211dd.png)
- Todos creen que es necesaria la Ley de Transparencia, sin embargo, la mayoría no la conocen ¿porqué?
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916498/dcdec766-8594-11e6-80fb-1bdb2628d1a1.png)
- La mayoría cree que sería más fácil interpretar la Ley si estuviera organizada en una tabla de criterios/obligaciones
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916547/0a167aee-8595-11e6-9e1b-8305286bbeb6.png)
- Todos creen en la importancia de un Portal de Transparencia.
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916567/1ddc2c18-8595-11e6-97ea-704ad7460998.png)

_Respecto a la herramienta_
- La gran mayoría cree que la herramienta sería buena tanto como herramienta para la participación ciudadana como para auditoría interna.
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916600/399002ea-8595-11e6-97c9-0654de330a7d.png)
- Se esperan encontrar mayormente: mapas, tabla de criterios de las diferentes leyes, gráficas de barras.
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916616/49e73bb8-8595-11e6-9b9a-0124596b133f.png)

**Conclusiones**

_Respecto a la ley_
- A pesar que la mayoría no conoce la Ley de Transparencia, todos creen que es necesaria. Esto representa una desinformación. Los encuestados entienden que la Transparencia es buena pero no saben los derechos que tienen con esta Ley.
- La interpretación de la Ley no está al alcance de un ciudadano de a pie, por eso la demanda de una tabla de criterios que simplifique su entendimiento.
- El Portal de Transparencia es considerado "Muy Importante", donde las instituciones puedan centralizar toda la información pública y donde se establezca el enlace con los ciudadanos. 

_Respecto a la herramienta_ 
- Los encuestados ven util tanto la herramienta participativa como la herramienta de auditoría -interna, entendemos que la mayoría de ciudadanos quieren poder participar en pro de la transparencia, y a la vez entienden que las instituciones dispongan de herramientas para mejorar sus servicios a la ciudadanía.
- Se espera encontrar mapas, ya que todos esperan poder localizar la transparencia de cada institución. Ademas la lista de criterios para poder entender la ley y participar. Por último los gráficos para diferentes comparativas.

**Analysis**
After 17 people that answer the 
[Google Form](https://docs.google.com/forms/d/1Co8xxQvXZOTEOTCXARCot78GXf5Tm8YPj0XVJaxHfFA/edit#responses)  the analysis is:
_Regarding the law_
- Most participants don't know Transparency Law
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916464/c6c92a20-8594-11e6-8e95-120cdb41bc74.png)
- All participants think that Transparency Law is required, however, most don't know it. Why?
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916501/e06a3974-8594-11e6-8585-02898b81d2eb.png)
- Most participants think that will be easily to interpret if Transparency Law will be structured in a criteria table.
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916536/0159ff3e-8595-11e6-86b3-96a06d24aa06.png)
- All participants thinks Transparency Portal is important
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916572/21beeb7c-8595-11e6-962d-6e0ebadfc3ec.png)

_Regardless with tool_
- Most participans think that tool would be good as tool for citizen participation as tool for internal audit.
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916598/3635961e-8595-11e6-8f89-be3629d8a381.png)
- Participants expect to find maps, criteria tables from different laws and bar charts
  ![image](https://cloud.githubusercontent.com/assets/17151589/18916623/4f6442d4-8595-11e6-9b01-5d911e9eebe4.png)

**Conclusions**

_Regardless the law_
- Although most do not know the Transparency Law, everyone thinks it is necessary. This is misinformation. The participants understand that Transparency is good but they don't know what rights they have with the Law.
- The interpretation of the law is not within reach of an ordinary citizen, so the demand for a table of criteria that simplify their understanding.
- The Transparency Portal is considered "very important", where institutions to centralize all public information and where the link with citizens is established.

_Regardless the tool_
- The participants see useful a transparency tool as intern audit and tool for citizen participation. We understand that everyone want to participate to help Transparency and moreover, they understand that the public institutions have tools to improve the citizens services.
- The participants expect to find maps, they hope to locate the transparency of each institution. Furthermore criteria table to understand the law and participate. Finally graphics for different comparative.
